version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - CHATTERBOX_ENDPOINT=${RUNPOD_CHATTERBOX_ENDPOINT}
      - KOKKORO_ENDPOINT=${RUNPOD_KOKKORO_ENDPOINT}
      - COQUI_ENDPOINT=${RUNPOD_COQUI_ENDPOINT}
      - RUNPOD_API_KEY=${RUNPOD_API_KEY}
    networks:
      - tts-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tts-network:
    driver: bridge
