name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and Push Chatterbox
      run: |
        docker build -t aparna0112/tts-chatterbox:latest ./models/chatterbox
        docker push aparna0112/tts-chatterbox:latest
    
    - name: Build and Push Kokkoro
      run: |
        docker build -t aparna0112/tts-kokkoro:latest ./models/kokkoro
        docker push aparna0112/tts-kokkoro:latest
    
    - name: Build and Push Coqui
      run: |
        docker build -t aparna0112/tts-coqui:latest ./models/coqui
        docker push aparna0112/tts-coqui:latest
